// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct ChangeNameArgs {
    pub new_name: String,
}

impl Reducer for ChangeNameArgs {
    const REDUCER_NAME: &'static str = "change_name";
}

#[allow(unused)]
pub fn change_name(new_name: String) {
    ChangeNameArgs { new_name }.invoke();
}

#[allow(unused)]
pub fn on_change_name(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &String) + Send + 'static,
) -> ReducerCallbackId<ChangeNameArgs> {
    ChangeNameArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let ChangeNameArgs { new_name } = __args;
        __callback(__identity, __addr, __status, new_name);
    })
}

#[allow(unused)]
pub fn once_on_change_name(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &String) + Send + 'static,
) -> ReducerCallbackId<ChangeNameArgs> {
    ChangeNameArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let ChangeNameArgs { new_name } = __args;
        __callback(__identity, __addr, __status, new_name);
    })
}

#[allow(unused)]
pub fn remove_on_change_name(id: ReducerCallbackId<ChangeNameArgs>) {
    ChangeNameArgs::remove_on_reducer(id);
}
