// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::message::Message;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct Chat {
    pub chat_id: u64,
    pub title: String,
    pub owner: u64,
    pub members: Vec<u64>,
    pub messages: Vec<Message>,
}

impl TableType for Chat {
    const TABLE_NAME: &'static str = "Chat";
    type ReducerEvent = super::ReducerEvent;
}

impl Chat {
    #[allow(unused)]
    pub fn filter_by_chat_id(chat_id: u64) -> TableIter<Self> {
        Self::filter(|row| row.chat_id == chat_id)
    }
    #[allow(unused)]
    pub fn find_by_chat_id(chat_id: u64) -> Option<Self> {
        Self::find(|row| row.chat_id == chat_id)
    }
    #[allow(unused)]
    pub fn filter_by_title(title: String) -> TableIter<Self> {
        Self::filter(|row| row.title == title)
    }
    #[allow(unused)]
    pub fn filter_by_owner(owner: u64) -> TableIter<Self> {
        Self::filter(|row| row.owner == owner)
    }
}
