// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct CreateChatArgs {
    pub title: String,
}

impl Reducer for CreateChatArgs {
    const REDUCER_NAME: &'static str = "create_chat";
}

#[allow(unused)]
pub fn create_chat(title: String) {
    CreateChatArgs { title }.invoke();
}

#[allow(unused)]
pub fn on_create_chat(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &String) + Send + 'static,
) -> ReducerCallbackId<CreateChatArgs> {
    CreateChatArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let CreateChatArgs { title } = __args;
        __callback(__identity, __addr, __status, title);
    })
}

#[allow(unused)]
pub fn once_on_create_chat(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &String) + Send + 'static,
) -> ReducerCallbackId<CreateChatArgs> {
    CreateChatArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let CreateChatArgs { title } = __args;
        __callback(__identity, __addr, __status, title);
    })
}

#[allow(unused)]
pub fn remove_on_create_chat(id: ReducerCallbackId<CreateChatArgs>) {
    CreateChatArgs::remove_on_reducer(id);
}
