// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct DeleteAccountArgs {}

impl Reducer for DeleteAccountArgs {
    const REDUCER_NAME: &'static str = "delete_account";
}

#[allow(unused)]
pub fn delete_account() {
    DeleteAccountArgs {}.invoke();
}

#[allow(unused)]
pub fn on_delete_account(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status) + Send + 'static,
) -> ReducerCallbackId<DeleteAccountArgs> {
    DeleteAccountArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let DeleteAccountArgs {} = __args;
        __callback(__identity, __addr, __status);
    })
}

#[allow(unused)]
pub fn once_on_delete_account(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status) + Send + 'static,
) -> ReducerCallbackId<DeleteAccountArgs> {
    DeleteAccountArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let DeleteAccountArgs {} = __args;
        __callback(__identity, __addr, __status);
    })
}

#[allow(unused)]
pub fn remove_on_delete_account(id: ReducerCallbackId<DeleteAccountArgs>) {
    DeleteAccountArgs::remove_on_reducer(id);
}
