// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct SendMessageArgs {
    pub chat_id: u64,
    pub content: String,
}

impl Reducer for SendMessageArgs {
    const REDUCER_NAME: &'static str = "send_message";
}

#[allow(unused)]
pub fn send_message(chat_id: u64, content: String) {
    SendMessageArgs { chat_id, content }.invoke();
}

#[allow(unused)]
pub fn on_send_message(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u64, &String) + Send + 'static,
) -> ReducerCallbackId<SendMessageArgs> {
    SendMessageArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let SendMessageArgs { chat_id, content } = __args;
        __callback(__identity, __addr, __status, chat_id, content);
    })
}

#[allow(unused)]
pub fn once_on_send_message(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u64, &String) + Send + 'static,
) -> ReducerCallbackId<SendMessageArgs> {
    SendMessageArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let SendMessageArgs { chat_id, content } = __args;
        __callback(__identity, __addr, __status, chat_id, content);
    })
}

#[allow(unused)]
pub fn remove_on_send_message(id: ReducerCallbackId<SendMessageArgs>) {
    SendMessageArgs::remove_on_reducer(id);
}
