// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct User {
    pub primary_id: u64,
    pub name: String,
    pub email: String,
    pub online: bool,
    pub identities: Vec<Identity>,
}

impl TableType for User {
    const TABLE_NAME: &'static str = "User";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for User {
    type PrimaryKey = u64;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.primary_id
    }
}

impl User {
    #[allow(unused)]
    pub fn filter_by_primary_id(primary_id: u64) -> TableIter<Self> {
        Self::filter(|row| row.primary_id == primary_id)
    }
    #[allow(unused)]
    pub fn find_by_primary_id(primary_id: u64) -> Option<Self> {
        Self::find(|row| row.primary_id == primary_id)
    }
    #[allow(unused)]
    pub fn filter_by_name(name: String) -> TableIter<Self> {
        Self::filter(|row| row.name == name)
    }
    #[allow(unused)]
    pub fn filter_by_email(email: String) -> TableIter<Self> {
        Self::filter(|row| row.email == email)
    }
    #[allow(unused)]
    pub fn find_by_email(email: String) -> Option<Self> {
        Self::find(|row| row.email == email)
    }
    #[allow(unused)]
    pub fn filter_by_online(online: bool) -> TableIter<Self> {
        Self::filter(|row| row.online == online)
    }
}
